[WIP]PROF-153 discussion
SW805F20/report pull request #106
Opened 2020-05-20 07:54 UTC by Eduardsen

2020-05-20 08:33 UTC, MathiasLybech requested changes

2020-05-20 08:33 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +
```suggestion
```

2020-05-20 08:33 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +
Fuck af med dit linjefarm

2020-05-20 08:33 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +In the beginning of the project these tended to be unfocused and not provide the necessary information.
Smid evt også en sætning ind omkring at daily stand up ikke var daily i starten. Men at det senere i processen blev det.

2020-05-20 08:33 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +when the socket type to be used for the program was initially chosen in \autoref{sec:sprint1-networking}, a large emphasis was put on the rate at which we could send messages.
```suggestion
When the socket type to be used for the program was initially chosen in \autoref{sec:sprint1-networking}, a large emphasis was put on the rate at which we could send messages.
```

2020-05-20 08:33 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +The first full scale test of the system and all its components took play on May 7th, as described in \autoref{sec:initial-test}.
```suggestion
The first full scale test of the system and all its components took place on May 7th, as described in \autoref{sec:initial-test}.
```

2020-05-20 08:33 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +The playing field scales based on the user input, meaning that requirement is supported, but fields have to be shaped like a rectangle or a square in order to support the current implementation of ge
```suggestion
The playing field scales based on the user input, meaning that requirement is supported, but fields have to be shaped like a rectangle or a square in order to support the current implementation of generating new goal zones.
```

2020-05-20 08:40 UTC, Eduardsen commented on sections/conclusion/discussion.tex
> +
fuck af med dit liv

2020-05-22 07:54 UTC, andpaacoke requested changes

2020-05-22 07:54 UTC, andpaacoke commented on sections/conclusion/discussion.tex
> +This has all been accomplished in the Unity game, as shown in REFREFREFREF.
????

2020-05-22 07:54 UTC, andpaacoke commented on sections/conclusion/discussion.tex
> +\todo{Den her sætning herunder. Er det godt nok sådan her? Eller er det at vi blamer tags?}
Altså vi der kunne måske godt spekuleres i forskellige årsager til det her men nej vi ved jo ikke hvad der er skyld i det

2020-05-22 07:54 UTC, andpaacoke commented on sections/conclusion/discussion.tex
> +\todo{Den her sætning herunder. Er det godt nok sådan her? Eller er det at vi blamer tags?}
Der kan evt. tilføjes noget med at vi har forsøgt at gøre op for den lave update rate ved implementering af lerping når det engang er merged ind

2020-05-22 07:55 UTC, andpaacoke commented
Synes afsnittet er helt fint men der mangler self stadig nogle ting med alle de todo's der er

2020-05-22 08:06 UTC, MathiasLybech requested changes

2020-05-22 08:06 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +This could also limit mobility, but during the test \todo{ref til st afsnit 18 maj} the game was played outdoors using a mobile network.
Den er på develop nu, så du kan godt lave en autoref til den

2020-05-22 08:06 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +As explained in \todo{18 maj ref}, there were some slight issues in terms of updates when playing the game outside.
tilføj autoref

2020-05-22 08:06 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +The non-functional requirements to be evaluated through a usability test.
```suggestion
The non-functional requirements were ideally to be evaluated through a usability test.
However, due to the circumstances, this was not possible.
```

2020-05-22 08:06 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +A usability test was conducted in \todo{ref til 18 maj}, but it could not be conducted properly due to the circumstances.
```suggestion
Instead a more unstructured test was conducted with the group as described in \todo{ref til 18 maj}.
```

2020-05-22 08:06 UTC, MathiasLybech commented on sections/conclusion/discussion.tex
> +The reason for this issue has not been pinpointed, and it could have been caused by an unstable connection to the mobile network.
Vi modtog jo ikke opdateringerne på netværket til hosten, men vi konkluderer det ikke rigtigt. Det er nok meget fint.

2020-05-22 08:43 UTC, MathiasLybech approved these changes

2020-05-22 08:53 UTC, andpaacoke approved these changes

2020-05-22 09:15 UTC, merged