PROJ-205 beskrivelse af lerping
SW805F20/report pull request #116
Opened 2020-05-20 11:30 UTC by andpaacoke

2020-05-20 11:38 UTC, Tekrus requested changes

2020-05-20 11:38 UTC, Moesgaarda commented on sections/sprint-5/lerping.tex
> +The slow update rate made the movement of game objects jerky, meaning it was difficult for the players that were testing to have a real time feeling of their position.
```suggestion
The slow update rate made the movement of game objects jerky, meaning it was difficult for the players who were testing to have a real-time feeling of their position.
```

2020-05-20 11:38 UTC, Moesgaarda commented on sections/sprint-5/lerping.tex
> +A requirement for dead reckoning is to have information about acceleration and velocity of the different game objects.
```suggestion
A requirement for dead reckoning is to have information about the acceleration and velocity of the different game objects.
```

2020-05-20 11:38 UTC, Moesgaarda commented on sections/sprint-5/lerping.tex
> +Instead the Unity function \textit{Lerping} was used, which finds the linear interpolates between two points.
```suggestion
Instead, the Unity function \texttt{lerping} was used, which finds the linear interpolation between two points.
```

2020-05-20 11:38 UTC, Moesgaarda commented on sections/sprint-5/lerping.tex
> +Lerping is calculated on the client side and the code in \autoref{lst:ball_position} calculates the position of the ball for each frame.
```suggestion
Lerping is calculated on the client-side and the code in \autoref{lst:ball_position} calculates the position of the ball for each frame.
```

2020-05-20 11:38 UTC, Moesgaarda commented on sections/sprint-5/lerping.tex
> +Through testing with mock data, it shows that calculating linear interpolates for each frame results in much smoother movement for each object in the game, which creates a more pleasant view for the
```suggestion
Through testing with mock data, it shows that calculating linear interpolates for each frame results in a much smoother movement for each object in the game, which creates a more pleasant view for the players, as well as creating a more immersive and real-time feeling to the game.
```

2020-05-20 11:47 UTC, Tekrus approved these changes

2020-05-22 07:57 UTC, Fatdet approved these changes

2020-05-22 08:03 UTC, merged