[WIP] PROJ-46 - Our process
SW805F20/report pull request #23
Opened 2020-03-06 12:50 UTC by MathiasLybech

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Our process was inspired from Essence, which is previously described in \autoref{sec:essence}.
```suggestion
Our process was inspired by Essence, which is previously described in \autoref{sec:essence}.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Previous semesters we have been working from a highly Scrum inspired process, but we decided that we wanted to try a new organization this semester.
```suggestion
We have been working with a highly Scrum inspired process during previous semesters, but we decided that we wanted to try a new organization this semester.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +One person has the role as a \textit{Challenger}.
```suggestion
One person has the \textit{Challenger} role.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Another person has the role as \textit{Anchor}.
```suggestion
Another person has the \textit{Anchor} role.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +This person is responsible for changes the process and is in charge of leading evaluations of the process.
```suggestion
This person is responsible for changes to the process and is in charge of leading evaluations of the process.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The rest of the group functions as \textit{Responders}
```suggestion
The rest of the group functions as \textit{Responders}.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The role as \textit{Child} is fluctuating between the group.
```suggestion
The \textit{Child} role fluctuates between members of the group.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Everyone has the possibility to add suggestions to improve the idea and give other perspectives on the project.
```suggestion
Everyone has the possibility to add suggestions to improve an idea and give other perspectives on the project.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Everyone can make suggestions to tasks that they find useful for the project.
```suggestion
Everyone can make suggestions of tasks that they find useful for the project.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The priority is then $reward - time$, which is an arbitrary number to indicate how important it is.
```suggestion
The priority of a task is then calculated as $reward - time$, which is an arbitrary number to indicate how important it is.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The Challenger then chooses the most important features from discussed often based on the highest priority, as \textit{Chosen for Development}.
```suggestion
The Challenger then chooses the most important features from the \textit{Discussed} column, often based on the highest priority, as \textit{Chosen for Development}.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +They will review the pull request together, where they will discuss the code and ensure that the quality of it is high.
```suggestion
They will review the pull request together, where they will discuss the code and ensure that the quality of it is acceptable.
```

2020-03-09 10:03 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Previous semesters people have reviewed the code separately, which leads to less comments as the code was not discussed.
```suggestion
Previous semesters people have reviewed the code separately, which leads to less comments as the code was not discussed between reviewers.
```

2020-03-12 13:36 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +However, we have chosen to keep sprints, stand-up meetings and retrospective meetings from Scrum as these can compliment Essence.
```suggestion
However, we have chosen to keep sprints, stand-up meetings and retrospective meetings from Scrum as these can complement Essence.
```

2020-03-12 13:36 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The process of prioritizing tasks are further described in the following section.
```suggestion
The process of prioritizing tasks is further described in the following section.
```

2020-03-12 13:36 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The left most column is the \textit{suggested} column.
```suggestion
The leftmost column is the \textit{Suggested} column.
```

2020-03-12 13:36 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Previous semesters people have reviewed the code separately, which leads to less comments as the code was not discussed between reviewers.
```suggestion
On previous semesters people have reviewed the code separately, which leads to less comments as the code was not discussed between reviewers.
```

2020-03-12 14:28 UTC, jenspetur94 requested changes
flyt afsnittet til sprint 1 og skriv introduktionen om sådan at den fortæller at vi startede ud med noget scrum værk og så skiftede over til det her halvejs gennem sprintet

2020-03-13 08:49 UTC, Eduardsen commented on sections/sprint-1/our-process.tex
> +We have been working with a ScrumBut approach in the beginning of the semester, but we decided that we wanted to try a new organization this semester, and during the courses of \textit{Software Innov
```suggestion
We have been working with a ScrumBut approach in the beginning of the semester, but we decided that we wanted to try a new organization this semester, and during the course of \textit{Software Innovation} we decided to pivot, changing the process.
```

2020-03-13 08:56 UTC, Eduardsen commented on sections/sprint-1/our-process.tex
> +We have been working with a ScrumBut approach in the beginning of the semester, but we decided that we wanted to try a new organization this semester, and during the courses of \textit{Software Innov
```suggestion
We have been working with a ScrumBut approach in the beginning of the semester, but we decided that we wanted to try a new organization this semester, and during the \textit{Software Innovation} course we decided to pivot, changing our process.
```

2020-03-13 09:00 UTC, Eduardsen approved these changes

2020-03-13 10:29 UTC, jenspetur94 approved these changes

2020-03-13 10:30 UTC, merged