deployment diagram
SW805F20/report pull request #26
Opened 2020-03-10 13:05 UTC by Eduardsen

![image](https://user-images.githubusercontent.com/22811794/76314993-21568e00-62d8-11ea-86af-435dbf4605f3.png)

2020-03-12 14:28 UTC, Eduardsen commented
![image](https://user-images.githubusercontent.com/22811794/76531865-1cc7dc00-6476-11ea-9d50-f6585f9b3400.png)

2020-03-12 14:35 UTC, Tekrus requested changes

2020-03-12 14:35 UTC, Moesgaarda commented on sections/sprint-2/deploymentdiagram.tex
> +The pozyx system node contains two components.
```suggestion
The Pozyx system node contains two components.
```

2020-03-12 14:35 UTC, Moesgaarda commented on sections/sprint-2/deploymentdiagram.tex
> +These are the anchors and the tags needed to generate positioning data with the pozyx hardware.
```suggestion
These are the anchors and the tags needed to generate positioning data with the Pozyx hardware.
```

2020-03-12 14:35 UTC, Moesgaarda commented on sections/sprint-2/deploymentdiagram.tex
> +These pozyx components generate artifacts in terms of positional data for the location of the players.
```suggestion
These Pozyx components generate artifacts in terms of positional data for the location of the players and the ball.
```

2020-03-12 14:35 UTC, Moesgaarda commented on sections/sprint-2/deploymentdiagram.tex
> +The host node is associated with the clients through a UDP connection in order to communicate the positional data.
```suggestion
The host node is dependent on the positional data artifact, instead, the component receives the positional data and transforms it for communication.
The host application component also contains an interface component, which is the interface that the person using the host component will interact with, in the form of a terminal application for the early version of the system.
The host node is associated with the clients through a UDP connection in order to communicate the positional data.
```

2020-03-12 14:35 UTC, Moesgaarda commented on sections/sprint-2/deploymentdiagram.tex
> +The mobile clients also contain interface components, which is how the users interact with that part of the system.
```suggestion
The mobile clients also contain interface components, which is how the users interact with that part of the system.
This interface is the virtual playing field generated in Unity, that the users see in the headset.
```

2020-03-12 14:40 UTC, Eduardsen commented on sections/sprint-2/deploymentdiagram.tex
> +The host node is associated with the clients through a UDP connection in order to communicate the positional data.
linje 22 er jo et blow up

2020-03-13 08:11 UTC, Tekrus approved these changes

2020-03-13 08:18 UTC, MathiasLybech approved these changes

2020-03-13 08:31 UTC, merged