Daniel readthrough
SW805F20/report pull request #29
Opened 2020-03-17 10:49 UTC by Moesgaarda

2020-03-17 11:13 UTC, MathiasLybech requested changes

2020-03-17 11:13 UTC, MathiasLybech commented on sections/sprint-1/our-process.tex
> +As described in \autoref{sec:essence}, a bi-focus of this project will be to attempt using the Essence process model as taught by the software innovation course.
```suggestion
As described in \autoref{sec:essence}, a bi-focus of this project will be to attempt using the Essence process model as taught by the Software Innovation course.
```

2020-03-18 08:33 UTC, MathiasLybech approved these changes

2020-03-18 08:48 UTC, andpaacoke approved these changes

2020-03-18 08:48 UTC, merged