PROJ-82 : Retrospective
SW805F20/report pull request #37
Opened 2020-03-26 13:03 UTC by Moesgaarda

2020-03-26 13:31 UTC, jenspetur94 requested changes

2020-03-26 13:31 UTC, jenspetur94 commented on sections/sprint-2/conclusion.tex
> +Generally, the biggest reason that it is difficult is to estimate how much remains of a given task, is that the definitions of done are not precise enough.
```suggestion
Generally, the biggest reason that it is difficult to estimate how much remains of a given task, is that the definitions of done are not precise enough.
```

2020-03-27 08:07 UTC, jenspetur94 approved these changes

2020-03-27 09:52 UTC, MathiasLybech requested changes

2020-03-27 09:52 UTC, MathiasLybech commented on sections/sprint-2/conclusion.tex
> +To battle this, it was decided to remove the prioritization of tasks where we would assign a reward, cost, and priority.
Jeg er ikke stor fan af denne formulering. Det lyder som om, at der automatisk ville komme en bedre DoD ved at fjerne Reward, Cost og priority.

2020-03-27 09:52 UTC, MathiasLybech commented on sections/sprint-2/conclusion.tex
> +	\item{What am I working on now?}
```suggestion
	\item{What am I working on now?}
	\item{When will my task be completed?}
```

2020-03-27 09:57 UTC, MathiasLybech approved these changes

2020-03-27 10:00 UTC, merged