Unity section
SW805F20/report pull request #4
Opened 2020-02-14 09:30 UTC by Eduardsen

2020-02-14 09:49 UTC, andpaacoke requested changes

2020-02-14 09:49 UTC, andpaacoke commented on sections/sprint-1/unity-intro.tex
> +As defined in FUK, this project aims to create a team-building augmented reality game.
Lav nu en ordentlig todo 😡

2020-02-14 11:48 UTC, MathiasLybech approved these changes

2020-02-17 08:33 UTC, andpaacoke approved these changes

2020-02-17 08:41 UTC, merged