JP sprint 1 readthrough
SW805F20/report pull request #42
Opened 2020-03-30 10:40 UTC by jenspetur94

2020-03-31 06:13 UTC, Tekrus requested changes

2020-03-31 06:13 UTC, Moesgaarda commented on sections/sprint-1/networking.tex
>  When TCP sends data, it requires an acknowledgment from the receiver that the data has been received.
Hvorfor fjerne reliability? Det er en af de vigtige dele ved TCP - jeg ville nok hellere slå den sammen med den næste linje hvis noget

2020-04-01 09:06 UTC, jenspetur94 commented on sections/sprint-1/networking.tex
>  When TCP sends data, it requires an acknowledgment from the receiver that the data has been received.
ja det kunne være en god idé. Synes bare at det var lidt spøjst sådan som det var sat op

2020-04-03 07:16 UTC, Tekrus approved these changes

2020-04-03 07:22 UTC, MathiasLybech approved these changes

2020-04-03 07:24 UTC, merged