Brian rettelser
SW805F20/report pull request #48
Opened 2020-04-07 08:18 UTC by Eduardsen

2020-04-07 08:29 UTC, MathiasLybech approved these changes

2020-04-07 08:33 UTC, andpaacoke approved these changes
Det er sikkert meget fint 😃

2020-04-07 08:34 UTC, Tekrus requested changes

2020-04-07 08:34 UTC, Moesgaarda commented on sections/sprint-2/joininggames.tex
> +Another option is to make use of the Zero Configuration Networking(Zeroconf) protocol.
```suggestion
Another option is to make use of the Zero Configuration Networking (Zeroconf) protocol.
```

2020-04-07 08:34 UTC, Moesgaarda commented on sections/sprint-2/joininggames.tex
> +Another option is to make use of the Zero Configuration Networking(Zeroconf) protocol.
ABBR LIST???

2020-04-07 08:44 UTC, Eduardsen commented on sections/sprint-2/joininggames.tex
> +Another option is to make use of the Zero Configuration Networking(Zeroconf) protocol.
fuck

2020-04-08 07:06 UTC, Tekrus approved these changes

2020-04-08 07:06 UTC, merged