New network implementation discussion
SW805F20/report pull request #53
Opened 2020-04-16 10:55 UTC by Eduardsen

2020-04-16 12:17 UTC, Fatdet approved these changes

2020-04-21 08:31 UTC, MathiasLybech requested changes

2020-04-21 08:31 UTC, MathiasLybech commented on sections/sprint-4/networking-updates.tex
> +\autoref{sec:sprint3-uppaal} defines the way the protocol was envisioned to work based on the choice made in \autoref{sec:sprint1-networking}, where UDP sockets were selected as the type to be used f
```suggestion
Section \ref{sec:sprint3-uppaal} defines the way the protocol was envisioned to work based on the choice made in \autoref{sec:sprint1-networking}, where UDP sockets were selected as the type to be used for this project.
```

2020-04-21 08:31 UTC, MathiasLybech commented on sections/sprint-4/networking-updates.tex
> +\autoref{sec:sprint3-uppaal} defines the way the protocol was envisioned to work based on the choice made in \autoref{sec:sprint1-networking}, where UDP sockets were selected as the type to be used f
Hvis man bruger autoref vil section stå med småt.

2020-04-21 08:45 UTC, Eduardsen commented on sections/sprint-4/networking-updates.tex
> +\autoref{sec:sprint3-uppaal} defines the way the protocol was envisioned to work based on the choice made in \autoref{sec:sprint1-networking}, where UDP sockets were selected as the type to be used f
din mor står med småt

2020-04-21 08:46 UTC, MathiasLybech approved these changes

2020-04-21 08:55 UTC, merged