[WIP] PROJ-6 - Swi process
SW805F20/report pull request #6
Opened 2020-02-14 11:40 UTC by MathiasLybech

2020-02-14 12:01 UTC, andpaacoke requested changes

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +For the process of the project development, we have chosen to work with essence.
```suggestion
For the process of the project development, we have chosen to work with Essence. 
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +    By using different views and roles to represent problems and solutions, Essence try to facilitate a range of viewpoints of how a problem needs to be understood and solved.
```suggestion
    By using different views and roles to represent problems and solutions, Essence tries to facilitate a range of viewpoints of how a problem needs to be understood and solved.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +    \item \textit{Process innovation} is Software solutions offering the user new or radically improved ways to produce products or services.
```suggestion
    \item \textit{Process innovation} is software solutions offering the user new or radically improved ways to produce products or services.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +There are 2 well established software development paradigms, the document oriented paradigm and agile paradigm.
```suggestion
There are two well established software development paradigms, the document oriented paradigm and agile paradigm.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +The document oriented paradigm showed software developers as being document oriented.
```suggestion
The document oriented paradigm shows software developers as being document oriented. 
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +The requirements were static and allowed for a top down waterfall approach to software development, which pays small attention to creativity and innovation.
```suggestion
The requirements are static and allows for a top down waterfall approach to software development, which pays small attention to creativity and innovation.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +The agile paradigm saw software development as user-oriented.
```suggestion
The agile paradigm sees software development as user-oriented.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +Requirements were presumed dynamic as customers learns about options and constraints within the course of the project.
```suggestion
Requirements are presumed dynamic as customers learn about options and constraints within the course of the project.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +The most important features of this paradigm is that requirements are not completely known when the projects start.
```suggestion
The most important features of this paradigm are that requirements are not completely known when the projects starts.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +Within the team organization in Essence roles are used to create heterogeneity in teams, to ensure diverse points on views and to ensure cohesion despite diversity.
```suggestion
Within the team organization in Essence, roles are used to create heterogeneity in teams, to ensure diverse points on views and to ensure cohesion despite diversity.
```

2020-02-14 12:01 UTC, andpaacoke commented on sections/introduction/swi-process.tex
> +\textit{Anchor} is the one responsible to for leading evaluations but does not decide consequences.
```suggestion
\textit{Anchor} is the one responsible for leading evaluations but does not decide consequences.
```

2020-02-14 12:14 UTC, Tekrus requested changes

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +Previous semesters we have worked with an agile scrum approach, but this semester we are working with Essence.
```suggestion
Previous semesters we have worked with an agile approach inspired by Scrum, however, this semester we are attempting to apply the Essence approach.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +The basic idea of Essence is to stimulate diverse thinking in the team, even though our team shares a similar background of a bachelors degree in Software.
```suggestion
The basic idea of Essence is to encourage diverse thinking in the team, even though all members of our team shares a similar background as bachelors in Software.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +Essence uses two strategies to support value creation:
hvad er value creation?

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +\subsection{Four variants of innovation}
Skriv et par linjer om hvorfor vi pludselig snakker om innovation.

Evt. noget med at fokuset på at essence understøtter innovation på en anden måde end traditionel agil?

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +There are 2 well established software development paradigms, the document oriented paradigm and agile paradigm.
```suggestion
There are 2 well established software development paradigms: the document oriented paradigm, which we know from the waterfall approach and agile paradigm which we know from for example extreme programming and Scrum.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +The author of Essence considers the new emerging paradigm called the Pragmatic paradigm.
```suggestion
The author of Essence considers the new emerging paradigm called the pragmatic paradigm.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +The document oriented paradigm showed software developers as being document oriented.
overvej at slette denne og de følgende suggestions hvis du applier den jeg har hvor vi nævner typerne på linje linje 27

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +The amount of data available, software libraries, hardware components etc. increases a lot every day.
```suggestion
The amount of data available, software libraries, hardware components is steadily increasing, leading to hypercomplex software projects.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +This results in hypercomplex software projects.
```suggestion
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +The roles are persistent.
```suggestion
As a rule of thumb, the roles are  persistent meaning that a member will have the same role for the duration of the project.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +A member will have the same role for the duration of the project.
```suggestion
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +The roles in Essence is compatible with agile software development.
```suggestion
The roles in Essence is compatible with agile software development, making it possible to combine Essence with other processes like Scrum.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +Hereby it would be possible to combine Essence with other software processes like Scrum.
```suggestion
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +    \item Anchor.
```suggestion
    \item Anchor
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +The rest of the team is not allowed to criticize the child, but they are however allowed to ignore its suggestions.
```suggestion
The rest of the team is not allowed to criticize the child, but they are however allowed to ignore the persons suggestions.
```

2020-02-14 12:14 UTC, Moesgaarda commented on sections/introduction/swi-process.tex
> +If necessary, the anchor can intervene and remove threats to the teams ability to develop ambitious responses.
tror det her skal uddybes lidt - er det bombetrusler? ebola? corona? blokade af arbejdsopgaver?

2020-02-17 08:57 UTC, jenspetur94 approved these changes

2020-02-17 08:57 UTC, jenspetur94 commented on sections/introduction/swi-process.tex
> +The basic idea of Essence is to encourage diverse thinking in the team, even though all members of our team shares a similar background as bachelors in Software.
```suggestion
The basic idea of Essence is to encourage diverse thinking in the team, even though all members of our team share a similar background as bachelors in Software.
```

2020-02-17 08:57 UTC, jenspetur94 commented on sections/introduction/swi-process.tex
> +There are different kinds of innovation which are important within Essence, as the roles considers the different types of innovation.
"as the roles considers the different types of innovation" giver ikke rigtig mening. Forstår ikke helt hvad du mener med den sætning

2020-02-17 08:57 UTC, jenspetur94 commented on sections/introduction/swi-process.tex
> +The document oriented paradigm showed software developers as being document oriented.
```suggestion
The document oriented paradigm portrayed software developers as being document oriented. 
```
muligvis ? 🤔

2020-02-17 08:57 UTC, jenspetur94 commented on sections/introduction/swi-process.tex
> +The document oriented paradigm showed software developers as being document oriented.
eller sees ligesom den næste paragraph

2020-02-17 08:57 UTC, jenspetur94 commented on sections/introduction/swi-process.tex
> +The amount of data available, software libraries, hardware components is steadily increasing, leading to hypercomplex software projects.
```suggestion
The amount of data, software libraries and hardware components available is steadily increasing, leading to hypercomplex software projects.
```

2020-02-17 08:57 UTC, jenspetur94 commented on sections/introduction/swi-process.tex
> +The roles in Essence is compatible with agile software development, making it possible to combine Essence with other processes like Scrum.
```suggestion
The roles in Essence are compatible with agile software development, making it possible to combine Essence with other processes like Scrum.
```

2020-02-17 08:57 UTC, jenspetur94 commented on sections/introduction/swi-process.tex
> +There are these 4 following roles:
```suggestion
There are the four roles in essence:
```

2020-02-17 09:23 UTC, Moesgaarda commented on sections/introduction/introduction.tex
> +\input{sections/introduction/project-idea.tex}
```suggestion
\input{sections/introduction/project-idea}
```

2020-02-17 09:24 UTC, Tekrus approved these changes

2020-02-17 09:38 UTC, andpaacoke approved these changes

2020-02-17 09:39 UTC, merged