[WIP] PROJ-139 - remove essence
SW805F20/report pull request #77
Opened 2020-05-05 09:30 UTC by MathiasLybech

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +This semester our process has been inspired by the process Essence taught in the Software Innovation course.
```suggestion
This semester our process has been inspired by the \texttt{Essence} process taught in the Software Innovation course.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +We have been working with a ScrumBut approach in previous semesters, but we decided that we wanted to try a different process this semester as we learned more about the Essence approach.\\
```suggestion
We have been working with a ScrumBut approach during previous semesters, but we decided that we wanted to try to improve our process by taking inspiration from a different process this semester.\\
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +To make the report fit this format, it has been split into 5 sprints that we will go through during the semester, where each sprint has a length of 3 weeks.
```suggestion
To make the report fit this format, it has been split into 5 sprints that fit the length of the semester, with each sprint lasting three weeks, except for sprint 5 which will only last two weeks.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The things that we primarily used from Essence was the team organization.
```suggestion
The main aspect of Essence we drew inspiration from was the team organization.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Another member has the \textit{Anchor} role, and is responsible for changes to the process and is in charge of leading the stand up meeting, retrospective and evaluations of the process.
```suggestion
Another member has the \textit{Anchor} role, and is responsible for changes to the process as well as in charge of leading the stand up meetings, retrospectives and evaluations of the process.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Within the team organization, in Essence, roles are used to create heterogeneity in teams, to ensure diverse points on views and to ensure cohesion despite diversity.
```suggestion
Within the team organization, in Essence, roles are used to create heterogeneity in teams, to ensure diverse points of view and to ensure cohesion despite diversity.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The roles also ensure that the team understands the problem domain, and see potentials in the technology domain.
see potentials? ved ikke lieg med den formulering, er ikke helt sikker på hvad det skal mene

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +As a rule of thumb, the roles are persistent meaning that a member will have the same role for the duration of the project.
```suggestion
The roles are persistent as a rule of thumb, meaning that a member will have the same role for the duration of the project.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +There are four roles in essence:
```suggestion
There are four roles in Essence:
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The role of \textit{Child} can ask any questions and make propositions that are opposite of previous decisions.
```suggestion
The role of \textit{Child} can ask any questions and make propositions that are in opposition to previous decisions.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The rest of the team is not allowed to criticize the child, but they are however allowed to ignore the person's suggestions.
```suggestion
The rest of the team is not allowed to criticize the \textit{Child}, but they are however allowed to ignore their suggestions.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Outsiders are also allowed to take this role.
```suggestion
Outsiders are also allowed to assume this role.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +Outsiders are also allowed to take this role.
outsiders? som i folk udenfor projektet?

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +\textit{Responders} are the developers in the team, and they are usually the majority within the team.
```suggestion
\textit{Responders} are the developers in the team, and are usually the majority within the team.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +This role formulates and explains the Challenge, prioritizes features and accepts the solutions.
```suggestion
This role formulates and explains the challenge, prioritizes features and accepts the solutions.
```

2020-05-06 13:21 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +\textit{Anchor} is the one responsible for leading evaluations but does not decide the consequences.
```suggestion
The \textit{Anchor} is the one responsible for leading evaluations, but does not decide the consequences.
```

2020-05-07 08:55 UTC, MathiasLybech commented on sections/introduction/our-process.tex
> +Outsiders are also allowed to take this role.
Jeg har fjernet denne linje. Den var nok egentlig ikke nødvendig.

2020-05-07 08:55 UTC, MathiasLybech commented on sections/introduction/our-process.tex
> +The roles also ensure that the team understands the problem domain, and see potentials in the technology domain.
Der menes at teamet ser potentielle løsninger. Jeg har forsøgt at omformulere den.

2020-05-08 07:07 UTC, Eduardsen commented on sections/introduction/our-process.tex
> +The roles also tries ensure that the team understands the problem domain, and see the potential solutions in the technology domain.
```suggestion
The roles also try to ensure that the team understands the problem domain, and that it sees the potential solutions in the technology domain.
```

2020-05-08 08:26 UTC, andpaacoke requested changes

2020-05-08 08:26 UTC, andpaacoke commented on sections/introduction/our-process.tex
> +The roles also tries ensure that the team understands the problem domain, and see the potential solutions in the technology domain.
```suggestion
The roles also tries to ensure that the team understands the problem domain, and see the potential solutions in the technology domain.
```

2020-05-08 08:26 UTC, andpaacoke commented on sections/introduction/our-process.tex
> +If necessary, the anchor can intervene and remove threats to the team's ability to develop ambitious responses.
```suggestion
If necessary, the \textit{Anchor} can intervene and remove threats to the team's ability to develop ambitious responses.
```

2020-05-08 08:26 UTC, andpaacoke commented on sections/introduction/our-process.tex
> +There can be more than one Challenger, but if there are they must agree on the product vision.
```suggestion
There can be more than one \text{Challenger}, but if there are they must agree on the product vision.
```

2020-05-08 08:26 UTC, andpaacoke commented on sections/introduction/our-process.tex
> +The child is one of the main sources of ideas and other perspectives on the project.
```suggestion
The \textit{Child} is one of the main sources of ideas and other perspectives on the project.
```

2020-05-08 08:26 UTC, andpaacoke commented on sections/introduction/our-process.tex
> +Responders work closely together with the \textit{Challenger}, so that the most important features are developed first.
```suggestion
\textit{Responders} work closely together with the \textit{Challenger}, so that the most important features are developed first.
```

2020-05-08 08:32 UTC, Eduardsen approved these changes

2020-05-08 08:33 UTC, andpaacoke approved these changes

2020-05-08 08:35 UTC, merged