PROJ-137 - Add resources to report
SW805F20/report pull request #78
Opened 2020-05-05 10:34 UTC by MathiasLybech

2020-05-05 11:52 UTC, Tekrus requested changes

2020-05-05 11:52 UTC, Moesgaarda commented on sections/resources.tex
> +\section*{Pozyx location Tracker}
```suggestion
\section*{Host software}
```

2020-05-05 11:52 UTC, Moesgaarda commented on sections/resources.tex
> +\section*{Unity}
```suggestion
\section*{Client game}
```

2020-05-05 11:52 UTC, Moesgaarda commented on sections/resources.tex
> +The code for the project can be found in the following Github repositories:
```suggestion
The code for the project can be found in the following GitHub repositories:
```

2020-05-05 11:52 UTC, Moesgaarda commented on sections/resources.tex
> +https://github.com/SW805F20/pozyx-location-tracker
```suggestion
\hyperlink{https://github.com/SW805F20/pozyx-location-tracker}{https://github.com/SW805F20/pozyx-location-tracker}
```

2020-05-05 11:52 UTC, Moesgaarda commented on sections/resources.tex
> +https://github.com/SW805F20/Unity
```suggestion
\hyperlink{https://github.com/SW805F20/Unity}{https://github.com/SW805F20/Unity}
```

2020-05-06 13:31 UTC, Tekrus approved these changes

2020-05-08 08:34 UTC, jenspetur94 approved these changes

2020-05-08 08:35 UTC, merged