PROJ-149 - Offset changes added to UPPAAL
SW805F20/report pull request #85
Opened 2020-05-12 12:49 UTC by MathiasLybech

2020-05-12 14:04 UTC, Tekrus requested changes

2020-05-12 14:04 UTC, Tekrus commented on sections/sprint-3/uppaal.tex
>  The updated version of the data format can be found in \autoref{app:network}
```suggestion
The updated version of the data format can be found in \autoref{app:network}.
```

2020-05-12 14:04 UTC, Moesgaarda commented on sections/sprint-3/uppaal.tex
> +\autoref{tab:goal-zone} has been updated to be 8 bit and not 16 bit.
to be 8 bit? hvad er 8 bit? og var der skrevet et sted at den var 16 før? Mener ikke at vi sendte det med før

2020-05-12 14:04 UTC, Moesgaarda commented on sections/sprint-3/uppaal.tex
> +With 16 bit the goal zone was previous able to be 655.36 m x 655.36 m, which would give the user room for customization to have much larger goal zones, but we deemed goal zones larger than 255 cm x 2
```suggestion
With 8 bit for the goal zone offsets, goals can not be larger than 255 cm x 255 cm, but we decided that it is a reasonable size.
Alternatively, the size could be increased to 16 bit, resulting in the goal zones having a maximum size of 655.36 m x 655.36 m, which would give the user room for customization to have much larger goal zones, but we deemed goal zones larger than 255 cm x 255 cm unnecessary for the time being.
```

2020-05-12 14:04 UTC, Moesgaarda commented on sections/sprint-3/uppaal.tex
> +        8 bit      & 16 bit   & 16 bit   & 8 bit        & 8 bit                                                   \\ \hline
her står bit, i de andre står der bits?

2020-05-13 08:03 UTC, MathiasLybech commented on sections/sprint-3/uppaal.tex
> +        8 bit      & 16 bit   & 16 bit   & 8 bit        & 8 bit                                                   \\ \hline
nu står der bits alle steder

2020-05-13 11:26 UTC, Tekrus requested changes

2020-05-13 11:26 UTC, Moesgaarda commented on sections/sprint-3/goal-position-generation.tex
> +To create the goal zone on the client side the center position is needed, which is the POSY and POSX.
```suggestion
To create the goal zone on the client side the center position is needed, which is the \texttt{POSY} and \texttt{POSX}.
```

2020-05-13 11:26 UTC, Moesgaarda commented on sections/sprint-3/goal-position-generation.tex
> +With 16 bit the playing this coordinate can range from $0$ to $2^{16}-1$.
```suggestion
We need this to be 16 bit, as 8 bit would only allow us to give a coordinate ranging from $0$ to $2^8 -1$, whereas 16 bit will increase the range to $0$ to $2^{16}-1$.
```

2020-05-13 11:31 UTC, Tekrus approved these changes

2020-05-13 11:40 UTC, jenspetur94 approved these changes

2020-05-13 11:40 UTC, merged