PROJ-15 sprint 1 goal
SW805F20/report pull request #9
Opened 2020-02-21 09:03 UTC by andpaacoke

2020-02-21 09:50 UTC, Tekrus requested changes
Måske skrive med at vi laver eksperimenter og at vi bruger pozyx til at danne baggrund for projektet?

2020-02-21 09:50 UTC, Moesgaarda commented on sections/sprint-1/sprint-goal.tex
> +In this sprint we want to learn more about how we can visualize the game for the users so they can see them selves in the game as well as the playing field.
```suggestion
In this sprint, we want to learn more about how we can visualize the game for the users so they can see themselves in the game as well as the playing field.
```

2020-02-21 09:50 UTC, Moesgaarda commented on sections/sprint-1/sprint-goal.tex
> +We want to look at how we can get the playing field's as well as the players' positions in an accurate way with fast updates.
```suggestion
We want to look at how we can get the playing field as well as the players' positions in an accurate way with fast updates.
```

2020-02-21 09:50 UTC, Moesgaarda commented on sections/sprint-1/sprint-goal.tex
> +As this is the first sprint of the project, the main focus is to gain more knowlegde about the different aspects of the project, and to gain a shared vision amongst the group members of how the game
```suggestion
As this is the first sprint of the project, the main focus is to gain more knowledge about the different aspects of the project and to gain a shared vision amongst the group members of how the game is going to work.
```

2020-02-21 09:50 UTC, Moesgaarda commented on sections/sprint-1/sprint-goal.tex
> +The shared vision will be achieved by making prototypes of the game as well as architectual diagrams of how different components in the game will work together.
```suggestion
The shared vision will be achieved by making prototypes of the game as well as architectural diagrams of how different components in the game will work together.
```

2020-02-24 10:53 UTC, Tekrus approved these changes

2020-02-24 10:55 UTC, jenspetur94 approved these changes

2020-02-24 10:55 UTC, merged